export const ADDITIONAL_THEMES = `
  "neon-cyber": {
    label: "Neon Cyber",
    createdAt: "2026-03-11",
    styles: {
      light: {
        background: "#fdfcff",
        foreground: "#0d0221",
        card: "#ffffff",
        "card-foreground": "#0d0221",
        popover: "#ffffff",
        "popover-foreground": "#0d0221",
        primary: "#00e5ff",
        "primary-foreground": "#001015",
        secondary: "#f1ecff",
        "secondary-foreground": "#1a0a3e",
        muted: "#f4f3ff",
        "muted-foreground": "#6b6392",
        accent: "#ff2afc",
        "accent-foreground": "#ffffff",
        destructive: "#ff4b6e",
        "destructive-foreground": "#ffffff",
        border: "#e8e5ff",
        input: "#eceaff",
        ring: "#00e5ff",
        "chart-1": "#00e5ff",
        "chart-2": "#ff2afc",
        "chart-3": "#39ff14",
        "chart-4": "#ffe600",
        "chart-5": "#ff6a00",
        sidebar: "#f6f4ff",
        "sidebar-foreground": "#0d0221",
        "sidebar-primary": "#00e5ff",
        "sidebar-primary-foreground": "#001015",
        "sidebar-accent": "#eceaff",
        "sidebar-accent-foreground": "#1a0a3e",
        "sidebar-border": "#eceaff",
        "sidebar-ring": "#00e5ff",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "1.4rem",
        "shadow-color": "hsl(265 100% 30%)",
        "shadow-opacity": "0.2",
        "shadow-blur": "8px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "3px",
        "letter-spacing": "-0.025em",
        spacing: "0.27rem",
      },

      dark: {
        background: "#0d0221",
        foreground: "#e9e6ff",
        card: "#140533",
        "card-foreground": "#e9e6ff",
        popover: "#140533",
        "popover-foreground": "#e9e6ff",
        primary: "#00e5ff",
        "primary-foreground": "#001015",
        secondary: "#1a0a3e",
        "secondary-foreground": "#dcd6ff",
        muted: "#1a0a3e",
        "muted-foreground": "#7c6f9f",
        accent: "#ff2afc",
        "accent-foreground": "#ffffff",
        destructive: "#ff4b6e",
        "destructive-foreground": "#ffffff",
        border: "#2d1b69",
        input: "#2d1b69",
        ring: "#00e5ff",
        "chart-1": "#00e5ff",
        "chart-2": "#ff2afc",
        "chart-3": "#39ff14",
        "chart-4": "#ffe600",
        "chart-5": "#ff6a00",
        sidebar: "#090019",
        "sidebar-foreground": "#e9e6ff",
        "sidebar-primary": "#00e5ff",
        "sidebar-primary-foreground": "#001015",
        "sidebar-accent": "#1a0a3e",
        "sidebar-accent-foreground": "#00e5ff",
        "sidebar-border": "#2d1b69",
        "sidebar-ring": "#00e5ff",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "1.4rem",
        "shadow-color": "hsl(190 100% 50%)",
        "shadow-opacity": "0.35",
        "shadow-blur": "12px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
        "letter-spacing": "-0.025em",
        spacing: "0.27rem",
      },
    },
  },
`;
